{{- with  .Values.adminPassword}}
{{- if .secret.create }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secretName) | default dict }}
{{- $password := (get $secret "password") | default (randAlphaNum 32) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.secretName}}
{{- if .secret.keepSecretOnRemove }}
  annotations:
    "helm.sh/resource-policy": "keep"
{{- end }}
stringData:
  currentPassword: "admin"
  password: {{ $password | quote }}
{{- end }}
{{- end }}