{{- range  .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.name}}
  namespace: {{$.Values.argoCDNamespace}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  {{- with .source }}
  source: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .destination }}
  destination: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .ignoreDifferences }}
  ignoreDifferences: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if .syncPolicy }}
  syncPolicy: {{ toYaml .syncPolicy | nindent 4 }}
  {{- else }}
  {{- include "defaultSyncPolicy" . | nindent 2 }}
  {{- end }}
{{- end }}


{{- define "defaultSyncPolicy" }}
syncPolicy:
  automated: 
    prune: true
    selfHeal: true
    allowEmpty: false
    syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
    retry:
        limit: 5
{{- end }}