{{- range  .Values.apps }}
{{- if .private }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: 
  name: "{{.name}}-repo"
spec:
  refreshInterval: 1h
  secretStoreRef:
  {{- toYaml $.Values.privateRepoSecrets.secretStoreRef | nindent 4 }}
  target:
    creationPolicy: Owner
    template:
      metadata:
        namespace: argo-cd
        labels:
          argocd.argoproj.io/secret-type: repository
    stringData:
      url: {{.repoURL}}
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: "{{$.Values.privateRepoSecrets.secretPrefix}}{{.name}}"
{{- end }}
{{- end }}

