{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .Values.adminSecretName) | default dict }}
{{- $password := (get $secret "password") | default (randAlphaNum 20) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.adminSecretName}}
{{- if .Values.keepSecretsOnRemove }}
  annotations:
    "helm.sh/resource-policy": "keep"
{{- end }}
stringData:
  config.env: |
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD={{ $password | quote }}
