{{- range .Values.userSecretNames }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace . ) | default dict }}
{{- $password := (get $secret "password") | default (randAlphaNum 20) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ . }}
{{- if $.Values.keepSecretsOnRemove }}
  annotations:
    "helm.sh/resource-policy": "keep"
{{- end }}
stringData:
  CONSOLE_ACCESS_KEY: {{ . | quote }}
  CONSOLE_SECRET_KEY: {{ $password | quote }}
---
{{- end }}