{{- range .Values.stores }}
apiVersion: external-secrets.io/v1beta1
kind: {{- if  .clusterScoped }} ClusterSecretStore {{ else }} SecretStore {{- end }}
metadata:
  name: {{ .name }}
  {{- if not .clusterScoped }}
  namespace: {{ .namespace }}
  {{- end }}
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    {{- if $.Values.aws.enabled }}
    aws:
      service: {{ .aws.service }}
      region: {{ $.Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .name }}
            namespace: {{ .namespace }}
    {{- end }}
---            
{{- end }}